[build]
builder = "NIXPACKS"

[env]
NODE_ENV = "production"

[[services]]
name = "yelp-ai"
root = "server"           # <— important
start = "npm start"       # uses server/package.json scripts.start
YELP_API_KEY="ripc0bHRllBNdQeejgeyCxlGIjgwCQ6zmghfEbsIwHdRME1aBqOEMPpBEt0Lq0phlu05o6E2YRrmADfoW18iPb5LThHLUbP0XIgXoMKoGRM8EbJi7ncogkt2ufqgaHYx"
YELP_USE_AI="true"
DEFAULT_CURRENCY="CAD"
