[build]
builder = "NIXPACKS"

[env]
NODE_ENV = "production"

[services]
name = "yelp-ai"
root = "server"           # <— important
start = "npm start"       # uses server/package.json scripts.start
YELP_API_KEY= "Bq-8T-9KGXkpy6aLsj4oURPwvJCyZiYZBOttHhQ5CfT0GYRtestCqFAxm_sGAXQAwEDZka32Ey6_-Hnm3S9ou1SymQPcyI0WjQqxTrmklX28ZUf67M2SUheMDYzZaHYx"
YELP_USE_AI="false"
DEFAULT_CURRENCY="CAD"
